package org.payio.wallet.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import org.payio.wallet.model.data.Cryptocurrency;
import org.payio.wallet.model.data.Wallet;

import org.payio.wallet.database.CryptocurrencyDao;
import org.payio.wallet.database.WalletDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cryptocurrencyDaoConfig;
    private final DaoConfig walletDaoConfig;

    private final CryptocurrencyDao cryptocurrencyDao;
    private final WalletDao walletDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cryptocurrencyDaoConfig = daoConfigMap.get(CryptocurrencyDao.class).clone();
        cryptocurrencyDaoConfig.initIdentityScope(type);

        walletDaoConfig = daoConfigMap.get(WalletDao.class).clone();
        walletDaoConfig.initIdentityScope(type);

        cryptocurrencyDao = new CryptocurrencyDao(cryptocurrencyDaoConfig, this);
        walletDao = new WalletDao(walletDaoConfig, this);

        registerDao(Cryptocurrency.class, cryptocurrencyDao);
        registerDao(Wallet.class, walletDao);
    }
    
    public void clear() {
        cryptocurrencyDaoConfig.clearIdentityScope();
        walletDaoConfig.clearIdentityScope();
    }

    public CryptocurrencyDao getCryptocurrencyDao() {
        return cryptocurrencyDao;
    }

    public WalletDao getWalletDao() {
        return walletDao;
    }

}
